import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { normalizeConfig } from '../src/validation.mjs';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
const config=JSON.parse(fs.readFileSync(path.join(root,'data','config.json'),'utf8'));
const normalized=normalizeConfig(config,config);
if(normalized.radio.streamUrl !== config.radio.streamUrl) throw new Error('streamUrl inválida');
for(const required of ['src/server.mjs','public/admin/index.html','.env.example']) if(!fs.existsSync(path.join(root,required))) throw new Error('Falta '+required);
console.log('Radio Periquín Cloud: OK · config v'+config.contentVersion+' · '+config.programs.length+' programas · '+config.stories.length+' cuentos');
